import mergePy from "../../wasm/merge_font.py?raw";

/** The fontTools merge script, shared by the wasm worker and the exporters. */
export default mergePy;

const MAIN_MARKER = 'if __name__ == "__main__":';

/** Serialize a plain JS value as a Python literal (strings/numbers/bools/objects). */
function pyLiteral(value: unknown, indent: number): string {
  const inner = " ".repeat(indent + 4);
  const close = " ".repeat(indent);
  if (value === null || value === undefined) return "None";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "boolean") return value ? "True" : "False";
  if (typeof value === "number") return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    return (
      "[\n" +
      value.map((v) => inner + pyLiteral(v, indent + 4)).join(",\n") +
      "\n" +
      close +
      "]"
    );
  }
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) return "{}";
    return (
      "{\n" +
      entries
        .map(
          ([k, v]) =>
            `${inner}${JSON.stringify(k)}: ${pyLiteral(v, indent + 4)}`,
        )
        .join(",\n") +
      "\n" +
      close +
      "}"
    );
  }
  return "None";
}

/** Read a big-endian uint32 at an offset (0 when out of range). */
function u32(data: Uint8Array, offset: number): number {
  if (data.length < offset + 4) return 0;
  return (
    ((data[offset]! << 24) |
      (data[offset + 1]! << 16) |
      (data[offset + 2]! << 8) |
      data[offset + 3]!) >>>
    0
  );
}

/** Extension matching the actual sfnt bytes (inputs may be decompressed). */
function sniffExtension(data: Uint8Array, fallback: string): string {
  switch (u32(data, 0)) {
    case 0x74746366: // 'ttcf'
      return ".ttc";
    case 0x774f4632: // 'wOF2'
      return ".woff2";
    case 0x4f54544f: // 'OTTO'
      return ".otf";
    case 0x774f4646: // 'wOFF'
      return ".woff";
    case 0x00010000:
    case 0x74727565: // 'true'
    case 0x74797031: // 'typ1'
      return ".ttf";
    default:
      return fallback;
  }
}

/** Basename without directories; extension corrected to the sniffed bytes. */
export function fontFileName(originalName: string, data: Uint8Array): string {
  const base = (originalName.split(/[\\/]/).pop() || "font").trim() || "font";
  const dot = base.lastIndexOf(".");
  const stem = dot > 0 ? base.slice(0, dot) : base;
  const fallbackExt = dot > 0 ? base.slice(dot).toLowerCase() : ".ttf";
  return stem + sniffExtension(data, fallbackExt);
}

/**
 * Output stem for generated files: "Family-Subfamily", subfamily omitted when
 * empty (an unset styleName inherits the mono base's subfamily, so callers
 * pass that fallback in). Keeps Regular etc. so different styles don't
 * overwrite each other on download.
 */
export function outputFileStem(family: string, subfamily: string): string {
  const clean = (s: string) =>
    s
      .replace(/[\\/:*?"<>|]+/g, "")
      .replace(/\s+/g, " ")
      .trim();
  const f = clean(family) || "CJKonospace";
  const st = clean(subfamily);
  return st ? `${f}-${st}` : f;
}

interface ArchiveFont {
  /** original file name (used as the zip entry, de-duplicated if needed) */
  name: string;
  data: Uint8Array;
}

export interface ArchiveInput {
  mono: ArchiveFont;
  cjk: ArchiveFont;
  /** the exact payload handed to merge_font.py (wasm and CLI share it) */
  params: Record<string, unknown>;
  /** effective subfamily for output/zip names (see outputFileStem) */
  subfamily?: string;
}

/**
 * Build an offline bundle: build.py (merge implementation plus the chosen
 * parameters and bundled font file names baked in) alongside the two input
 * fonts. Unzip anywhere and run with no arguments:
 *
 *     uv run build.py
 *
 * Requires only fontTools (declared inline via PEP 723), nothing from
 * CJKonospace, and the parameters are plain editable Python literals.
 */
export async function buildStandaloneArchive(
  input: ArchiveInput,
): Promise<{ blob: Blob; outName: string; zipName: string }> {
  const { strToU8, zipSync } = await import("fflate");
  const idx = mergePy.indexOf(MAIN_MARKER);
  const body = (idx === -1 ? mergePy : mergePy.slice(0, idx)).trimEnd();

  const monoName =
    input.mono.name === input.cjk.name
      ? `mono-${input.mono.name}`
      : input.mono.name;
  const cjkName =
    input.mono.name === input.cjk.name
      ? `cjk-${input.cjk.name}`
      : input.cjk.name;
  const format =
    (input.params["format"] as string | undefined) === "woff2"
      ? "woff2"
      : "ttf";
  const family =
    (
      (input.params["familyName"] as string | undefined) || "CJKonospace"
    ).trim() || "CJKonospace";
  const stem = outputFileStem(family, input.subfamily ?? "");
  const outName = `${stem}.${format}`;
  const script = `#!/usr/bin/env python3
"""Standalone CJK + monospace merge bundle (generated by CJKonospace).

Unzip anywhere and run with no arguments (fonts and parameters are bundled):

    uv run build.py

Dependencies (fontTools, brotli and numpy) are declared inline, so no manual
install is needed. numpy only feeds the accelerated glyf decode path.

The merge parameters chosen in the app are embedded as PARAMS below; edit
them freely. To merge different fonts, point MONO_FILE/CJK_FILE at them.
No other part of CJKonospace is required to run this file.
"""

${body}


MONO_FILE = ${JSON.stringify(monoName)}
CJK_FILE = ${JSON.stringify(cjkName)}
OUT_FILE = ${JSON.stringify(outName)}

PARAMS = ${pyLiteral(input.params, 0)}


def main():
    meta = merge(MONO_FILE, CJK_FILE, OUT_FILE, PARAMS)
    print("wrote %s (%s glyphs added)" % (OUT_FILE, meta.get("added")))


if __name__ == "__main__":
    main()
`;
  const dir = stem.replace(/[\\/:*?"<>|]+/g, "") || "CJKonospace";
  const zipName = `${dir}.zip`;
  const blob = new Blob(
    [
      zipSync({
        [`${dir}/build.py`]: strToU8(script),
        [`${dir}/${monoName}`]: input.mono.data,
        [`${dir}/${cjkName}`]: input.cjk.data,
      }),
    ],
    { type: "application/zip" },
  );
  return { blob, outName, zipName };
}
