import mergePy from "../../wasm/merge_font.py?raw";

/** The fontTools merge script, shared by the wasm worker and the exporters. */
export default mergePy;

const MAIN_MARKER = 'if __name__ == "__main__":';

/** Serialize a plain JS value as a Python literal (strings/numbers/bools/objects). */
function pyLiteral(value: unknown, indent: number): string {
  const inner = " ".repeat(indent + 4);
  const close = " ".repeat(indent);
  if (value === null || value === undefined) return "None";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "boolean") return value ? "True" : "False";
  if (typeof value === "number") return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    return (
      "[\n" +
      value.map((v) => inner + pyLiteral(v, indent + 4)).join(",\n") +
      "\n" +
      close +
      "]"
    );
  }
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) return "{}";
    return (
      "{\n" +
      entries
        .map(
          ([k, v]) =>
            `${inner}${JSON.stringify(k)}: ${pyLiteral(v, indent + 4)}`,
        )
        .join(",\n") +
      "\n" +
      close +
      "}"
    );
  }
  return "None";
}

/**
 * Build a self-contained build.py: the merge implementation plus the chosen
 * parameters baked in as a PARAMS dict. Requires only fontTools, nothing from
 * CJKonospace, and the parameters are plain editable Python literals.
 */
export function buildStandaloneScript(params: Record<string, unknown>): string {
  const idx = mergePy.indexOf(MAIN_MARKER);
  const body = (idx === -1 ? mergePy : mergePy.slice(0, idx)).trimEnd();
  return `#!/usr/bin/env python3
"""Standalone CJK + monospace merge script (generated by CJKonospace).

Depends only on fontTools:  pip install fonttools

Usage:
    python build.py mono.ttf cjk.ttf [out.ttf]

The merge parameters chosen in the app are embedded as PARAMS below; edit them
freely. No other part of CJKonospace is required to run this file.
"""

import sys

${body}


PARAMS = ${pyLiteral(params, 0)}


def main():
    if len(sys.argv) < 3:
        print("usage: python build.py mono.ttf cjk.ttf [out.ttf]")
        raise SystemExit(2)
    mono_path, cjk_path = sys.argv[1], sys.argv[2]
    out_path = sys.argv[3] if len(sys.argv) > 3 else PARAMS["familyName"] + ".ttf"
    meta = merge(mono_path, cjk_path, out_path, PARAMS)
    print("wrote %s (%s glyphs added)" % (out_path, meta.get("added")))


if __name__ == "__main__":
    main()
`;
}
